Changed [callProc] args type. It accepts only primitive values.
LeonardSSH/ragemp-types pull request #13
Opened 2022-01-05 22:55 UTC by xYouLL

It seems that callProc accepts only primitive values.
JSON.stringify is required to pass objects from CEF to client.

2022-01-06 11:37 UTC, LeonardSSH requested changes

2022-01-06 11:37 UTC, LeonardSSH commented on index.d.ts
> +    callProc<T>(eventName: string, args: primitiveTypes): Promise<T>;
Better, I think we can set `...args: any[]`? As in the other cases, you can't know exactly what you want to pass.

No point in hard-typing args in such an environment.

2022-01-06 19:14 UTC, xYouLL commented on index.d.ts
> +    callProc<T>(eventName: string, args: primitiveTypes): Promise<T>;
It does accept only a primitive value, not an array of them.
For example if you want to pass an object to the client you should use JSON.stringify for it, in order for it to be converted in a string.

2022-01-06 19:25 UTC, LeonardSSH requested changes

2022-01-06 19:25 UTC, LeonardSSH commented on index.d.ts
> +type primitiveTypes = string | number | undefined | boolean | bigint | null | symbol;
Can we use `PascalCase`?

2022-01-06 19:25 UTC, LeonardSSH commented on index.d.ts
> +    callProc<T>(eventName: string, args: primitiveTypes): Promise<T>;
Same here.

2022-01-06 19:25 UTC, LeonardSSH commented on index.d.ts
> +type primitiveTypes = string | number | undefined | boolean | bigint | null | symbol;
Like:

```ts
type PrimitiveTypes = string | number | undefined | boolean | bigint | null | symbol;
```

2022-01-08 14:25 UTC, xYouLL commented
Done!

2022-01-08 14:32 UTC, merged